export const apresentacaoSobreMim = {
    saudacao: "Olá, eu sou o Bruno!",
    paragrafos: [
        "Atualmente atuo como desenvolvedor full stack, porém minha trajetória na área de Tecnologia da Informação teve início em 2005, quando comecei como técnico em manutenção de microcomputadores. Ao longo dos anos, adquiri sólida experiência com suporte técnico, atendimento a empresas e atuação em infraestrutura de redes, trabalhando com configuração e administração de servidores de domínio local, serviços de DHCP, servidores de arquivos e FTP, além de implantação e configuração de roteadores e ambientes corporativos.",
        "Em 2018, direcionei minha carreira para a área de desenvolvimento de software, passando a atuar na construção de aplicações, evolução de sistemas e melhoria contínua de processos tecnológicos.",
        "No front-end, trabalho principalmente com React, mantendo também experiência e interesse em ecossistemas como Next.js e Angular. Busco desenvolver interfaces responsivas, reutilizáveis e bem estruturadas, priorizando componentização, desacoplamento e uma experiência de navegação clara e eficiente para o usuário.",
        "No back-end, possuo experiência com Java, C#, PHP e Python, utilizando frameworks e tecnologias como Spring Boot, Quarkus, .NET / ASP.NET Core, Entity Framework e Laravel para desenvolvimento de APIs REST, implementação de regras de negócio, integrações entre sistemas e autenticação baseada em JWT.",
        "Atualmente participo do desenvolvimento de um projeto estratégico conduzido por uma grande empresa de tecnologia, com backend desenvolvido em Go (Golang) e arquitetura baseada em microsserviços orquestrados em Kubernetes. O sistema segue princípios de Clean Architecture e boas práticas de engenharia de software, utilizando tecnologias como PostgreSQL, GORM, Casbin para autorização, MinIO para armazenamento de objetos, OpenTelemetry para observabilidade e pipelines automatizados de CI/CD.",
        "Este projeto possui visão de evolução para se tornar uma solução corporativa de grande porte, com características de um ERP moderno, voltado para alta escalabilidade, segurança, integração entre módulos e suporte a operações críticas de negócio.",
        "Além disso, venho fortalecendo minha atuação em infraestrutura e práticas DevOps, utilizando ferramentas como Docker, Docker Swarm, Kubernetes, Jenkins e GitHub Actions para containerização, automação de pipelines, padronização de ambientes e melhoria da entrega contínua de software.",
        "No dia a dia, valorizo metodologias ágeis, colaboração entre equipes e melhoria incremental de processos e produtos. Por isso, práticas como Scrum, versionamento estruturado, revisão de código e foco em qualidade fazem parte da forma como organizo minhas entregas e acompanho a evolução dos projetos."
    ]
};
